//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppCitaMedica.cistasmedicas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClinicasSWSoap", Namespace="http://tempuri.org/")]
    public partial class ClinicasSW : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LogueoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarUsuarioAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarUsuarioClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarUsuarioMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarCitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarClinicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCliente2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarHorarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEspecialidadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClinicasSW() {
            this.Url = "http://www.cistasmedicas.somee.com/ClinicasSW.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LogueoUsuarioCompletedEventHandler LogueoUsuarioCompleted;
        
        /// <remarks/>
        public event RegistrarUsuarioAdminCompletedEventHandler RegistrarUsuarioAdminCompleted;
        
        /// <remarks/>
        public event RegistrarUsuarioClienteCompletedEventHandler RegistrarUsuarioClienteCompleted;
        
        /// <remarks/>
        public event RegistrarUsuarioMedicoCompletedEventHandler RegistrarUsuarioMedicoCompleted;
        
        /// <remarks/>
        public event AgregarCitaCompletedEventHandler AgregarCitaCompleted;
        
        /// <remarks/>
        public event ListarCitaCompletedEventHandler ListarCitaCompleted;
        
        /// <remarks/>
        public event AgregarClienteCompletedEventHandler AgregarClienteCompleted;
        
        /// <remarks/>
        public event ListarClienteCompletedEventHandler ListarClienteCompleted;
        
        /// <remarks/>
        public event AgregarMedicoCompletedEventHandler AgregarMedicoCompleted;
        
        /// <remarks/>
        public event ListarMedicoCompletedEventHandler ListarMedicoCompleted;
        
        /// <remarks/>
        public event ListarClinicaCompletedEventHandler ListarClinicaCompleted;
        
        /// <remarks/>
        public event ListarCliente2CompletedEventHandler ListarCliente2Completed;
        
        /// <remarks/>
        public event ListarHorarioCompletedEventHandler ListarHorarioCompleted;
        
        /// <remarks/>
        public event ListarEspecialidadCompletedEventHandler ListarEspecialidadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogueoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LogueoUsuario(string user, string pass) {
            object[] results = this.Invoke("LogueoUsuario", new object[] {
                        user,
                        pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoUsuarioAsync(string user, string pass) {
            this.LogueoUsuarioAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void LogueoUsuarioAsync(string user, string pass, object userState) {
            if ((this.LogueoUsuarioOperationCompleted == null)) {
                this.LogueoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoUsuarioOperationCompleted);
            }
            this.InvokeAsync("LogueoUsuario", new object[] {
                        user,
                        pass}, this.LogueoUsuarioOperationCompleted, userState);
        }
        
        private void OnLogueoUsuarioOperationCompleted(object arg) {
            if ((this.LogueoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoUsuarioCompleted(this, new LogueoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarUsuarioAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegistrarUsuarioAdmin(string Email, string Pass) {
            object[] results = this.Invoke("RegistrarUsuarioAdmin", new object[] {
                        Email,
                        Pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAdminAsync(string Email, string Pass) {
            this.RegistrarUsuarioAdminAsync(Email, Pass, null);
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAdminAsync(string Email, string Pass, object userState) {
            if ((this.RegistrarUsuarioAdminOperationCompleted == null)) {
                this.RegistrarUsuarioAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarUsuarioAdminOperationCompleted);
            }
            this.InvokeAsync("RegistrarUsuarioAdmin", new object[] {
                        Email,
                        Pass}, this.RegistrarUsuarioAdminOperationCompleted, userState);
        }
        
        private void OnRegistrarUsuarioAdminOperationCompleted(object arg) {
            if ((this.RegistrarUsuarioAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarUsuarioAdminCompleted(this, new RegistrarUsuarioAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarUsuarioCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegistrarUsuarioCliente(string Email, string Pass) {
            object[] results = this.Invoke("RegistrarUsuarioCliente", new object[] {
                        Email,
                        Pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarUsuarioClienteAsync(string Email, string Pass) {
            this.RegistrarUsuarioClienteAsync(Email, Pass, null);
        }
        
        /// <remarks/>
        public void RegistrarUsuarioClienteAsync(string Email, string Pass, object userState) {
            if ((this.RegistrarUsuarioClienteOperationCompleted == null)) {
                this.RegistrarUsuarioClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarUsuarioClienteOperationCompleted);
            }
            this.InvokeAsync("RegistrarUsuarioCliente", new object[] {
                        Email,
                        Pass}, this.RegistrarUsuarioClienteOperationCompleted, userState);
        }
        
        private void OnRegistrarUsuarioClienteOperationCompleted(object arg) {
            if ((this.RegistrarUsuarioClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarUsuarioClienteCompleted(this, new RegistrarUsuarioClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarUsuarioMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegistrarUsuarioMedico(string Email, string Pass) {
            object[] results = this.Invoke("RegistrarUsuarioMedico", new object[] {
                        Email,
                        Pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarUsuarioMedicoAsync(string Email, string Pass) {
            this.RegistrarUsuarioMedicoAsync(Email, Pass, null);
        }
        
        /// <remarks/>
        public void RegistrarUsuarioMedicoAsync(string Email, string Pass, object userState) {
            if ((this.RegistrarUsuarioMedicoOperationCompleted == null)) {
                this.RegistrarUsuarioMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarUsuarioMedicoOperationCompleted);
            }
            this.InvokeAsync("RegistrarUsuarioMedico", new object[] {
                        Email,
                        Pass}, this.RegistrarUsuarioMedicoOperationCompleted, userState);
        }
        
        private void OnRegistrarUsuarioMedicoOperationCompleted(object arg) {
            if ((this.RegistrarUsuarioMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarUsuarioMedicoCompleted(this, new RegistrarUsuarioMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarCita(string Fecha, int Telefono, string Descripcion, int Cliente, int Clinica) {
            object[] results = this.Invoke("AgregarCita", new object[] {
                        Fecha,
                        Telefono,
                        Descripcion,
                        Cliente,
                        Clinica});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarCitaAsync(string Fecha, int Telefono, string Descripcion, int Cliente, int Clinica) {
            this.AgregarCitaAsync(Fecha, Telefono, Descripcion, Cliente, Clinica, null);
        }
        
        /// <remarks/>
        public void AgregarCitaAsync(string Fecha, int Telefono, string Descripcion, int Cliente, int Clinica, object userState) {
            if ((this.AgregarCitaOperationCompleted == null)) {
                this.AgregarCitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCitaOperationCompleted);
            }
            this.InvokeAsync("AgregarCita", new object[] {
                        Fecha,
                        Telefono,
                        Descripcion,
                        Cliente,
                        Clinica}, this.AgregarCitaOperationCompleted, userState);
        }
        
        private void OnAgregarCitaOperationCompleted(object arg) {
            if ((this.AgregarCitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCitaCompleted(this, new AgregarCitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CitaSW[] ListarCita() {
            object[] results = this.Invoke("ListarCita", new object[0]);
            return ((CitaSW[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCitaAsync() {
            this.ListarCitaAsync(null);
        }
        
        /// <remarks/>
        public void ListarCitaAsync(object userState) {
            if ((this.ListarCitaOperationCompleted == null)) {
                this.ListarCitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCitaOperationCompleted);
            }
            this.InvokeAsync("ListarCita", new object[0], this.ListarCitaOperationCompleted, userState);
        }
        
        private void OnListarCitaOperationCompleted(object arg) {
            if ((this.ListarCitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCitaCompleted(this, new ListarCitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarCliente(string Nombres, string Apellidos, int Telefono, string Email) {
            object[] results = this.Invoke("AgregarCliente", new object[] {
                        Nombres,
                        Apellidos,
                        Telefono,
                        Email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarClienteAsync(string Nombres, string Apellidos, int Telefono, string Email) {
            this.AgregarClienteAsync(Nombres, Apellidos, Telefono, Email, null);
        }
        
        /// <remarks/>
        public void AgregarClienteAsync(string Nombres, string Apellidos, int Telefono, string Email, object userState) {
            if ((this.AgregarClienteOperationCompleted == null)) {
                this.AgregarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarClienteOperationCompleted);
            }
            this.InvokeAsync("AgregarCliente", new object[] {
                        Nombres,
                        Apellidos,
                        Telefono,
                        Email}, this.AgregarClienteOperationCompleted, userState);
        }
        
        private void OnAgregarClienteOperationCompleted(object arg) {
            if ((this.AgregarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarClienteCompleted(this, new AgregarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClienteSW[] ListarCliente() {
            object[] results = this.Invoke("ListarCliente", new object[0]);
            return ((ClienteSW[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClienteAsync() {
            this.ListarClienteAsync(null);
        }
        
        /// <remarks/>
        public void ListarClienteAsync(object userState) {
            if ((this.ListarClienteOperationCompleted == null)) {
                this.ListarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClienteOperationCompleted);
            }
            this.InvokeAsync("ListarCliente", new object[0], this.ListarClienteOperationCompleted, userState);
        }
        
        private void OnListarClienteOperationCompleted(object arg) {
            if ((this.ListarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClienteCompleted(this, new ListarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarMedico(string Nombres, string Apellidos, string Email, int Telefono, int Horario, int Especialidad) {
            object[] results = this.Invoke("AgregarMedico", new object[] {
                        Nombres,
                        Apellidos,
                        Email,
                        Telefono,
                        Horario,
                        Especialidad});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarMedicoAsync(string Nombres, string Apellidos, string Email, int Telefono, int Horario, int Especialidad) {
            this.AgregarMedicoAsync(Nombres, Apellidos, Email, Telefono, Horario, Especialidad, null);
        }
        
        /// <remarks/>
        public void AgregarMedicoAsync(string Nombres, string Apellidos, string Email, int Telefono, int Horario, int Especialidad, object userState) {
            if ((this.AgregarMedicoOperationCompleted == null)) {
                this.AgregarMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarMedicoOperationCompleted);
            }
            this.InvokeAsync("AgregarMedico", new object[] {
                        Nombres,
                        Apellidos,
                        Email,
                        Telefono,
                        Horario,
                        Especialidad}, this.AgregarMedicoOperationCompleted, userState);
        }
        
        private void OnAgregarMedicoOperationCompleted(object arg) {
            if ((this.AgregarMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarMedicoCompleted(this, new AgregarMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MedicoSW[] ListarMedico() {
            object[] results = this.Invoke("ListarMedico", new object[0]);
            return ((MedicoSW[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarMedicoAsync() {
            this.ListarMedicoAsync(null);
        }
        
        /// <remarks/>
        public void ListarMedicoAsync(object userState) {
            if ((this.ListarMedicoOperationCompleted == null)) {
                this.ListarMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarMedicoOperationCompleted);
            }
            this.InvokeAsync("ListarMedico", new object[0], this.ListarMedicoOperationCompleted, userState);
        }
        
        private void OnListarMedicoOperationCompleted(object arg) {
            if ((this.ListarMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarMedicoCompleted(this, new ListarMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarClinica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClinicaSW[] ListarClinica() {
            object[] results = this.Invoke("ListarClinica", new object[0]);
            return ((ClinicaSW[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClinicaAsync() {
            this.ListarClinicaAsync(null);
        }
        
        /// <remarks/>
        public void ListarClinicaAsync(object userState) {
            if ((this.ListarClinicaOperationCompleted == null)) {
                this.ListarClinicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClinicaOperationCompleted);
            }
            this.InvokeAsync("ListarClinica", new object[0], this.ListarClinicaOperationCompleted, userState);
        }
        
        private void OnListarClinicaOperationCompleted(object arg) {
            if ((this.ListarClinicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClinicaCompleted(this, new ListarClinicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCliente2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClienteSW[] ListarCliente2() {
            object[] results = this.Invoke("ListarCliente2", new object[0]);
            return ((ClienteSW[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCliente2Async() {
            this.ListarCliente2Async(null);
        }
        
        /// <remarks/>
        public void ListarCliente2Async(object userState) {
            if ((this.ListarCliente2OperationCompleted == null)) {
                this.ListarCliente2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCliente2OperationCompleted);
            }
            this.InvokeAsync("ListarCliente2", new object[0], this.ListarCliente2OperationCompleted, userState);
        }
        
        private void OnListarCliente2OperationCompleted(object arg) {
            if ((this.ListarCliente2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCliente2Completed(this, new ListarCliente2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarHorario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HorarioSW[] ListarHorario() {
            object[] results = this.Invoke("ListarHorario", new object[0]);
            return ((HorarioSW[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarHorarioAsync() {
            this.ListarHorarioAsync(null);
        }
        
        /// <remarks/>
        public void ListarHorarioAsync(object userState) {
            if ((this.ListarHorarioOperationCompleted == null)) {
                this.ListarHorarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarHorarioOperationCompleted);
            }
            this.InvokeAsync("ListarHorario", new object[0], this.ListarHorarioOperationCompleted, userState);
        }
        
        private void OnListarHorarioOperationCompleted(object arg) {
            if ((this.ListarHorarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarHorarioCompleted(this, new ListarHorarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarEspecialidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EspecialidadSW[] ListarEspecialidad() {
            object[] results = this.Invoke("ListarEspecialidad", new object[0]);
            return ((EspecialidadSW[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarEspecialidadAsync() {
            this.ListarEspecialidadAsync(null);
        }
        
        /// <remarks/>
        public void ListarEspecialidadAsync(object userState) {
            if ((this.ListarEspecialidadOperationCompleted == null)) {
                this.ListarEspecialidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEspecialidadOperationCompleted);
            }
            this.InvokeAsync("ListarEspecialidad", new object[0], this.ListarEspecialidadOperationCompleted, userState);
        }
        
        private void OnListarEspecialidadOperationCompleted(object arg) {
            if ((this.ListarEspecialidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEspecialidadCompleted(this, new ListarEspecialidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CitaSW {
        
        private int idField;
        
        private string fechaField;
        
        private string descripcionField;
        
        private int clienteIdField;
        
        private int clinicaIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public int ClienteId {
            get {
                return this.clienteIdField;
            }
            set {
                this.clienteIdField = value;
            }
        }
        
        /// <remarks/>
        public int ClinicaId {
            get {
                return this.clinicaIdField;
            }
            set {
                this.clinicaIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EspecialidadSW {
        
        private int idField;
        
        private string descripcionField;
        
        private string honorariosField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Honorarios {
            get {
                return this.honorariosField;
            }
            set {
                this.honorariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HorarioSW {
        
        private int idField;
        
        private int medicoIdField;
        
        private string descripcionField;
        
        private string horaInicioField;
        
        private string horaFinField;
        
        private int diaIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int MedicoId {
            get {
                return this.medicoIdField;
            }
            set {
                this.medicoIdField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string HoraInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
            }
        }
        
        /// <remarks/>
        public string HoraFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
            }
        }
        
        /// <remarks/>
        public int DiaId {
            get {
                return this.diaIdField;
            }
            set {
                this.diaIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClinicaSW {
        
        private int idField;
        
        private string nombreClinicaField;
        
        private string latitudField;
        
        private string longitudField;
        
        private string telefonoField;
        
        private string direccionField;
        
        private int medicoIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NombreClinica {
            get {
                return this.nombreClinicaField;
            }
            set {
                this.nombreClinicaField = value;
            }
        }
        
        /// <remarks/>
        public string Latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        public string Longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public int MedicoId {
            get {
                return this.medicoIdField;
            }
            set {
                this.medicoIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MedicoSW {
        
        private int idField;
        
        private string nombresField;
        
        private string apellidosField;
        
        private string emailField;
        
        private string telefonoField;
        
        private int horarioIdField;
        
        private int especialidadIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public int HorarioId {
            get {
                return this.horarioIdField;
            }
            set {
                this.horarioIdField = value;
            }
        }
        
        /// <remarks/>
        public int EspecialidadId {
            get {
                return this.especialidadIdField;
            }
            set {
                this.especialidadIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClienteSW {
        
        private int idField;
        
        private string nombresField;
        
        private string apellidosField;
        
        private string telefonoField;
        
        private string emailField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogueoUsuarioCompletedEventHandler(object sender, LogueoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegistrarUsuarioAdminCompletedEventHandler(object sender, RegistrarUsuarioAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarUsuarioAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarUsuarioAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegistrarUsuarioClienteCompletedEventHandler(object sender, RegistrarUsuarioClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarUsuarioClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarUsuarioClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegistrarUsuarioMedicoCompletedEventHandler(object sender, RegistrarUsuarioMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarUsuarioMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarUsuarioMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarCitaCompletedEventHandler(object sender, AgregarCitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarCitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarCitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarCitaCompletedEventHandler(object sender, ListarCitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CitaSW[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CitaSW[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarClienteCompletedEventHandler(object sender, AgregarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarClienteCompletedEventHandler(object sender, ListarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClienteSW[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClienteSW[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarMedicoCompletedEventHandler(object sender, AgregarMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarMedicoCompletedEventHandler(object sender, ListarMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MedicoSW[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MedicoSW[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarClinicaCompletedEventHandler(object sender, ListarClinicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClinicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClinicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClinicaSW[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClinicaSW[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarCliente2CompletedEventHandler(object sender, ListarCliente2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCliente2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCliente2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClienteSW[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClienteSW[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarHorarioCompletedEventHandler(object sender, ListarHorarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarHorarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarHorarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HorarioSW[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HorarioSW[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarEspecialidadCompletedEventHandler(object sender, ListarEspecialidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEspecialidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEspecialidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EspecialidadSW[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EspecialidadSW[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591